# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cal2norm <- function(A, gIdx, Atranspose, TgCB_T) {
    .Call('_mixlasso_cal2norm', PACKAGE = 'mixlasso', A, gIdx, Atranspose, TgCB_T)
}

shrink <- function(A, gIdx, Atranspose, TgCB_T) {
    .Call('_mixlasso_shrink', PACKAGE = 'mixlasso', A, gIdx, Atranspose, TgCB_T)
}

XXeigen <- function(X, V, tIdx) {
    .Call('_mixlasso_XXeigen', PACKAGE = 'mixlasso', X, V, tIdx)
}

mixlassoLoop <- function(V, C, gIdx, Tglasso, tIdx, X, Y, intercept, num_nonpen, L, lambda, option, mu, NoVar, gamma, y_mis, alpha) {
    .Call('_mixlasso_mixlassoLoop', PACKAGE = 'mixlasso', V, C, gIdx, Tglasso, tIdx, X, Y, intercept, num_nonpen, L, lambda, option, mu, NoVar, gamma, y_mis, alpha)
}

treelassoLoop <- function(X, Y, C, gIdx, TauNorm, intercept, num_nonpen, lambda, option, mu) {
    .Call('_mixlasso_treelassoLoop', PACKAGE = 'mixlasso', X, Y, C, gIdx, TauNorm, intercept, num_nonpen, lambda, option, mu)
}

